// `.source/server.ts` is generated by the fumadocs-mdx bundler plugin (via
// `createMDX()` in next.config.mjs, or the `fumadocsMdx()` vite plugin in
// vitest.config.ts) the first time Next/Vitest runs. It is gitignored, so on
// a fresh checkout it does not exist yet.
//
// `tsc --noEmit` (the `prebuild` script) does its own module resolution and
// does not run that bundler plugin, so without this ambient fallback it
// fails with "Cannot find module '@/.source/server'" before the module has
// ever been generated. This shape mirrors `source.config.ts`'s schema
// (`pageSchema`/`metaSchema`) so `prebuild` type-checks pages the same way
// it will once the real file exists. Once the real generated file exists,
// TypeScript resolves to it directly and this declaration is ignored.
declare module '@/.source/server' {
  import type { DocsCollectionEntry } from 'fumadocs-mdx/runtime/server'
  import type { metaSchema, pageSchema } from 'fumadocs-core/source/schema'
  import type { z } from 'zod'

  export const docs: DocsCollectionEntry<string, z.infer<typeof pageSchema>, z.infer<typeof metaSchema>>
}
